### ISSUE TITLE
NEBP: Mgmt Select Launch Site

### ISSUE THREAD

**Issue by profFisher** [profFisher/NEBP_WV#19]
We need to select the launch site for October flight so that accommodations can be made

**Comment by CaCordwell** [comment]
Hi Marcus

I thought we set it already.  From all your research it was to be:

NW Texas - Vanderpool Texas

If you are okay with that location- I am fine w it as well.

From: Marcus Fisher ***@***.***>
Sent: Monday, January 23, 2023 3:27 PM
To: profFisher/NEBP_WV ***@***.***>
Cc: Candy Cordwell ***@***.***>; Assign ***@***.***>
Subject: [profFisher/NEBP_WV] NEBP: Mgmt Select Launch Site (Issue #19)


We need to select the launch site for October flight so that accommodations can be made

**Comment by CaCordwell** [comment]
Hi Marcus

I thought we set it already.  From all your research it was to be:

NW Texas - Vanderpool Texas

If you are okay with that location- I am fine w it as well.

**Comment by profFisher** [comment]
I have been scanning the map and I think we should do Odessa Texas, we don't have to get too far off main road. Odessa Texas is big enough that it can serve as a drop point for Helium Gas.

**Comment by profFisher** [comment]
Actually just a little NW of Odessa is Hobbs Texas would be best spot

**Comment by CaCordwell** [comment]
You are far ahead of me on this- I was trying to read they oath of totality and find it difficult to analyze.

[NASA - Google Maps and Solar Eclipse Paths: 2021 - 2040](https://eclipse.gsfc.nasa.gov/SEgoogle/SEgoogle2021.html)

Here is another one I found:
https://www.timeanddate.com/eclipse/solar/2023-october-14 

Hobbs NM is also fine.
